import { useState } from "react";
import { useLoaderData, useRouteError, Link } from "react-router";
import { boundary } from "@shopify/shopify-app-react-router/server";
import { authenticate } from "../shopify.server";
import { fetchShopifyInventory, getRoiMetrics, syncSubscriptionFromShopify } from "../models/inventory.server";
import { PLAN_PRICES, PLAN_NAMES } from "../utils/planLimits";

export const loader = async ({ request }) => {
  const { admin, session } = await authenticate.admin(request);
  const shop = session.shop;

  const { subscription } = await syncSubscriptionFromShopify(admin, shop);
  const inventoryData = await fetchShopifyInventory(admin, shop);
  const roi = await getRoiMetrics(shop, inventoryData.items);

  return {
    shop,
    subscription,
    totalVariants: inventoryData.items?.length || 0,
    roi,
  };
};

export default function RoiPage() {
  const { shop, subscription, totalVariants, roi } = useLoaderData();
  const [copied, setCopied] = useState(false);

  const planKey = subscription?.plan || "FREE";
  const planPrice = PLAN_PRICES[planKey] || 0;
  const planName = PLAN_NAMES[planKey] || "Starter / Free";

  // Calculate ROI Multiplier vs Plan Cost
  const roiMultiplier = planPrice > 0 
    ? (roi.totalEstimatedRoi / planPrice).toFixed(1) 
    : (roi.totalEstimatedRoi > 0 ? "∞" : "0.0");

  const handleCopySummary = () => {
    const text = `StockShield Financial ROI Report for ${shop}:\nTotal Revenue Recovered: $${roi.totalEstimatedRoi.toFixed(2)}\nRecovered Demand: $${roi.backInStockDemandValue.toFixed(2)}\nCatalog Protection: $${roi.catalogProtectionValue.toFixed(2)}\nSubscribers Notified: ${roi.notifiedSubscribers}/${roi.totalSubscribers}\nAutomations Executed: ${roi.totalAutomations} (${roi.restockCount} restocks, ${roi.autoHideCount} hides, ${roi.alertCount} alerts)`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  return (
    <div className="stock-container" style={{ paddingBottom: "40px" }}>
      {/* Top Header */}
      <div className="stock-header">
        <div>
          <h1>ROI &amp; Revenue Analytics</h1>
          <p>Real-time financial impact breakdown generated by StockShield inventory automations</p>
        </div>
        <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
          <button onClick={handleCopySummary} className="btn-secondary" style={{ fontSize: "12px", padding: "8px 14px" }}>
            {copied ? "✓ Report Copied!" : "Copy ROI Summary"}
          </button>
          <span className="stock-badge-active">Connected: {shop}</span>
        </div>
      </div>

      {/* Main Executive ROI Hero Banner */}
      <div
        style={{
          background: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)",
          borderRadius: "16px",
          padding: "28px 32px",
          marginBottom: "24px",
          color: "#ffffff",
          boxShadow: "0 12px 30px -5px rgba(15, 23, 42, 0.3)",
          position: "relative",
          overflow: "hidden",
        }}
      >
        <div
          style={{
            position: "absolute",
            top: "-60px",
            right: "-60px",
            width: "260px",
            height: "260px",
            borderRadius: "50%",
            background: "radial-gradient(circle, rgba(99, 102, 241, 0.35) 0%, rgba(15, 23, 42, 0) 70%)",
            pointerEvents: "none",
          }}
        />

        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: "24px", position: "relative", zIndex: 1 }}>
          <div style={{ flex: "1 1 360px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "8px" }}>
              <span style={{ background: "rgba(99, 102, 241, 0.25)", border: "1px solid rgba(129, 140, 248, 0.4)", color: "#a5b4fc", fontSize: "11px", fontWeight: "700", padding: "4px 12px", borderRadius: "14px", textTransform: "uppercase", letterSpacing: "0.5px" }}>
                Live Financial Impact
              </span>
              <span style={{ fontSize: "12px", color: "#94a3b8" }}>Active Subscription: <strong>{planName}</strong></span>
            </div>
            <h2 style={{ fontSize: "38px", fontWeight: "800", margin: "6px 0 8px 0", color: "#ffffff", letterSpacing: "-0.5px", display: "flex", alignItems: "baseline", gap: "12px" }}>
              ${(roi?.totalEstimatedRoi || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
              <span style={{ fontSize: "14px", fontWeight: "700", color: "#34d399", background: "rgba(52, 211, 153, 0.15)", border: "1px solid rgba(52, 211, 153, 0.35)", padding: "3px 12px", borderRadius: "14px" }}>
                {roiMultiplier}x ROI Return
              </span>
            </h2>
            <p style={{ margin: 0, fontSize: "14px", color: "#cbd5e1", lineHeight: "1.6", maxWidth: "680px" }}>
              Calculated preserved revenue and demand recovered by preventing out-of-stock bounce penalties and executing back-in-stock alerts across {totalVariants} catalog items.
            </p>
          </div>

          <div style={{ background: "rgba(255, 255, 255, 0.07)", border: "1px solid rgba(255, 255, 255, 0.12)", borderRadius: "12px", padding: "16px 20px", minWidth: "200px" }}>
            <div style={{ fontSize: "11px", color: "#94a3b8", fontWeight: "600", textTransform: "uppercase" }}>Monthly Subscription Cost</div>
            <div style={{ fontSize: "22px", fontWeight: "700", color: "#ffffff", marginTop: "4px" }}>
              ${planPrice.toFixed(2)} <span style={{ fontSize: "12px", color: "#cbd5e1", fontWeight: "normal" }}>/mo</span>
            </div>
            <div style={{ fontSize: "12px", color: "#34d399", marginTop: "4px", fontWeight: "600" }}>
              ✓ Yielding {roiMultiplier}x Return
            </div>
          </div>
        </div>
      </div>

      {/* 4 Pillars Breakdown Grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "16px", marginBottom: "24px" }}>
        <div className="table-card" style={{ padding: "20px" }}>
          <div style={{ fontSize: "12px", fontWeight: "600", color: "#64748b", textTransform: "uppercase", letterSpacing: "0.5px" }}>Recovered Demand</div>
          <div style={{ fontSize: "26px", fontWeight: "800", color: "#4f46e5", marginTop: "6px" }}>
            ${(roi?.backInStockDemandValue || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
          <div style={{ fontSize: "12px", color: "#64748b", marginTop: "4px" }}>
            From restock subscriber alerts
          </div>
        </div>

        <div className="table-card" style={{ padding: "20px", borderLeft: "4px solid #10b981" }}>
          <div style={{ fontSize: "12px", fontWeight: "600", color: "#065f46", textTransform: "uppercase", letterSpacing: "0.5px" }}>Catalog Protection</div>
          <div style={{ fontSize: "26px", fontWeight: "800", color: "#059669", marginTop: "6px" }}>
            ${(roi?.catalogProtectionValue || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
          </div>
          <div style={{ fontSize: "12px", color: "#047857", marginTop: "4px" }}>
            Prevented stockout bounce loss
          </div>
        </div>

        <div className="table-card" style={{ padding: "20px", borderLeft: "4px solid #e11d48" }}>
          <div style={{ fontSize: "12px", fontWeight: "600", color: "#9f1239", textTransform: "uppercase", letterSpacing: "0.5px" }}>Restock Buyers</div>
          <div style={{ fontSize: "26px", fontWeight: "800", color: "#be123c", marginTop: "6px" }}>
            {roi?.totalSubscribers || 0}
          </div>
          <div style={{ fontSize: "12px", color: "#9f1239", marginTop: "4px" }}>
            {roi?.notifiedSubscribers || 0} buyers notified on restock
          </div>
        </div>

        <div className="table-card" style={{ padding: "20px", borderLeft: "4px solid #d97706" }}>
          <div style={{ fontSize: "12px", fontWeight: "600", color: "#92400e", textTransform: "uppercase", letterSpacing: "0.5px" }}>Automation Actions</div>
          <div style={{ fontSize: "26px", fontWeight: "800", color: "#b45309", marginTop: "6px" }}>
            {roi?.totalAutomations || 0}
          </div>
          <div style={{ fontSize: "12px", color: "#92400e", marginTop: "4px" }}>
            {roi?.restockCount || 0} restocks &middot; {roi?.autoHideCount || 0} hides &middot; {roi?.alertCount || 0} alerts
          </div>
        </div>
      </div>

      {/* Detailed Methodology & Transparent Formula Panel */}
      <div className="table-card" style={{ padding: "24px" }}>
        <h3 style={{ fontSize: "17px", margin: "0 0 12px 0", color: "#0f172a", fontWeight: "700" }}>
          Transparent ROI Valuation Methodology
        </h3>
        <p style={{ margin: "0 0 20px 0", fontSize: "13px", color: "#64748b", lineHeight: "1.5" }}>
          StockShield calculates financial impact directly from observed store product prices, inventory movements, customer lead alerts, and automated catalog protection triggers.
        </p>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: "20px" }}>
          <div style={{ background: "#f8fafc", padding: "18px", borderRadius: "10px", border: "1px solid #e2e8f0" }}>
            <h4 style={{ margin: "0 0 8px 0", fontSize: "14px", color: "#1e293b", fontWeight: "700" }}>
              1. Back-In-Stock Demand Recovery Model
            </h4>
            <ul style={{ margin: 0, paddingLeft: "18px", fontSize: "12px", color: "#475569", lineHeight: "1.8" }}>
              <li><strong>Average Store Price:</strong> ${(roi?.averageProductPrice || 35.0).toFixed(2)} per item.</li>
              <li><strong>Notified Subscribers:</strong> 35% estimated e-commerce purchase conversion rate upon restock alert delivery.</li>
              <li><strong>Pending Pipeline Demand:</strong> 15% valuation for active waiting list subscribers.</li>
            </ul>
          </div>

          <div style={{ background: "#f8fafc", padding: "18px", borderRadius: "10px", border: "1px solid #e2e8f0" }}>
            <h4 style={{ margin: "0 0 8px 0", fontSize: "14px", color: "#1e293b", fontWeight: "700" }}>
              2. Catalog Stockout Protection Model
            </h4>
            <ul style={{ margin: 0, paddingLeft: "18px", fontSize: "12px", color: "#475569", lineHeight: "1.8" }}>
              <li><strong>Auto-Publish Restocks:</strong> 40% conversion salvage rate applied to restocked catalog items.</li>
              <li><strong>Zero-Stock Auto-Hiding:</strong> $8.50 bounce penalty protection value per item auto-hidden to preserve store search conversion rate.</li>
            </ul>
          </div>
        </div>

        <div style={{ marginTop: "20px", display: "flex", justifyContent: "flex-end", gap: "12px" }}>
          <Link to="/app/plan" className="btn-primary" style={{ fontSize: "13px", padding: "10px 18px" }}>
            Manage Subscription &amp; Plan →
          </Link>
        </div>
      </div>
    </div>
  );
}

export function ErrorBoundary() {
  return boundary.error(useRouteError());
}

export const headers = (headersArgs) => {
  return boundary.headers(headersArgs);
};
